export:
  pdf:
    fonts:
      normal: /opt/homebrew/Caskroom/font-udev-gothic-nf/2.2.0/UDEVGothic_NF_v2.2.0/UDEVGothicNF-Regular.ttf
      italic: /opt/homebrew/Caskroom/font-udev-gothic-nf/2.2.0/UDEVGothic_NF_v2.2.0/UDEVGothicNF-Italic.ttf
      bold: /opt/homebrew/Caskroom/font-udev-gothic-nf/2.2.0/UDEVGothic_NF_v2.2.0/UDEVGothicNF-Bold.ttf
      bold_italic: /opt/homebrew/Caskroom/font-udev-gothic-nf/2.2.0/UDEVGothic_NF_v2.2.0/UDEVGothicNF-BoldItalic.ttf
  dimensions:
    columns: 128
    rows: 36
